### ISSUE TITLE
Question about the design: why is there a mutex in the main structure?

### ISSUE THREAD

**Issue by owulveryck** [bmaupin/go-epub#50]
This is a thread to open the discussion about the need of a mutex in the main structure.

Wouldn't it be easier to declare the methods unsafe for concurrent use?

**Comment by bmaupin** [comment]
The mutex is there because of this: https://github.com/bmaupin/go-epub/pull/27

I guess it would certainly be easier if it wasn't there, but on the other hand it seems to add some level of thread-safety for very little cost.

I guess there's always a balance between the cost of maintaining certain features versus the benefit they bring.

I guess if you wanted to consider removing it, the next step might be to get some feedback from some of the other users of this library.

Thanks for all the feedback, by the way! I'm looking for help maintaining this project, if you're interested :D #28

**Comment by owulveryck** [comment]
Thanks for the answer.
I guess that we would have benefit from a failing test with the `-race` condition, but so far I agree, as it does not introduces a huge overhead, I don't see any need to change that.
